In [3]:
import numpy as np
a=np.array(np.random.randint(1,21,20))
print a
a.shape=(4,5)
print "Original Matrix"
print a
print "Sorting it column wise axis=0"
print np.sort(a,axis=0)
print "Sorting it row wise axis=1"
print np.sort(a,axis=1)
print "Sorting through a new column linear"
print np.sort(a,axis=np.newaxis)

[11 18 12 17 13 20 14 13 20 12  9  2  4  6 10  1 19 19  2  2]
Original Matrix
[[11 18 12 17 13]
 [20 14 13 20 12]
 [ 9  2  4  6 10]
 [ 1 19 19  2  2]]
Sorting it column wise axis=0
[[ 1  2  4  2  2]
 [ 9 14 12  6 10]
 [11 18 13 17 12]
 [20 19 19 20 13]]
Sorting it row wise axis=1
[[11 12 13 17 18]
 [12 13 14 20 20]
 [ 2  4  6  9 10]
 [ 1  2  2 19 19]]
Sorting through a new column linear
[ 1  2  2  2  4  6  9 10 11 12 12 13 13 14 17 18 19 19 20 20]


In [4]:
'''The question for this problem is found in the below link
    https://www.hackerrank.com/challenges/kangaroo/submissions/code/25883101
'''
import sys
x1,v1,x2,v2 = raw_input().strip().split(' ')
x1,v1,x2,v2 = [float(x1), float(v1), float(x2), float(v2)]
try:
    '''Checks for exceptions while dividing'''
    y = (x1-x2) / (v2-v1)                  #Number of jumps after which they will meet
    if y.is_integer() and y>=0:
        '''If y is an integer, it means (x1-x2) is completly divisible by (v2-v1) 
            and they do meet
        '''
        print "YES"
    else:
        print "NO"
except:
    '''Catches the divide by zero exception if any'''
    if x1 != x2:
        print "NO"
    else:
        print "YES"

4 2 3 5
NO
